### ISSUE TITLE
Start colima without rewriting `colima.yaml` config

### ISSUE THREAD

**Issue by stackptr** [abiosoft/colima#1004]
### Description

I want to use NixOS to manage the `colima.yaml` config for the default profile. NixOS will build a YAML File in a read-only filesystem and creates a symlink to it in the expected path. This fails because colima requires write permissions:

```
❯ colima start -p default --very-verbose
TRAC[0000] cmd ["limactl" "info"]                       
TRAC[0000] cmd ["system_profiler" "-json" "SPHardwareDataType"] 
TRAC[0000] cmd ["system_profiler" "-json" "SPHardwareDataType"] 
FATA[0000] error preparing config file: error writing yaml file: open /Users/corey/.colima/default/colima.yaml: permission denied 
```

When I move the symlink and copy the contents to the path, it seems that a template is used to write a new configuration file with the values of whatever was read in on startup. While it is great that this allows poorly formatted files to be legible after startup, I'd like a way to tell colima that this unnecessary. For example, `colima start --no-config-template` or `--read-only-config`.

**Comment by mirza-src** [comment]
I was having the same issue and was looking to open a PR and realized while going through the code that I can manage the default template in Nix instead of the profile config. [This](https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#setting-the-default-config) was the only reference I could find for it. Basically, whenever a new profile is started `$COLIMA_HOME/_templates/default.yaml` gets copied over to `$COLIMA_HOME/<profile-name>/colima.yaml` (for default profile `$COLIMA_HOME/default/colima.yaml`).

This allowed me to configure the `$COLIMA_HOME/_templates/default.yaml` in my home-manager config and avoid this error. Although this will not work once the profile is started, so any changes to the configuration afterwards will not be reflected to the existing profile unless the profile is deleted and recreated. I am very new to Nix but I imagine that this recreation could be handled in Nix somehow. This is not an issue for me (for now) as I do not foresee frequent changes to the configuration after initial system setup.

**Comment by abiosoft** [comment]
I would be closing this in favour of #613. 

You can follow up the issue over there.

**Comment by chrishrb** [comment]
> I was having the same issue and was looking to open a PR and realized while going through the code that I can manage the default template in Nix instead of the profile config. [This](https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#setting-the-default-config) was the only reference I could find for it. Basically, whenever a new profile is started `$COLIMA_HOME/_templates/default.yaml` gets copied over to `$COLIMA_HOME/<profile-name>/colima.yaml` (for default profile `$COLIMA_HOME/default/colima.yaml`).
> 
> This allowed me to configure the `$COLIMA_HOME/_templates/default.yaml` in my home-manager config and avoid this error. Although this will not work once the profile is started, so any changes to the configuration afterwards will not be reflected to the existing profile unless the profile is deleted and recreated. I am very new to Nix but I imagine that this recreation could be handled in Nix somehow. This is not an issue for me (for now) as I do not foresee frequent changes to the configuration after initial system setup.

Thanks, good idea! 💯  I'm also using nix and home-manager and managed to workaround this issue by adding an `onChange` command like this:

```nix
      home.file."./.colima/_templates/default.yaml" = {
        source = ./colima.yaml;
        onChange = ''cat ~/.colima/_templates/default.yaml > ~/.colima/default/colima.yaml'';
      };
```
