### ISSUE TITLE
How to persist db with parameter "-v" 

### ISSUE THREAD

**Issue by paynetiger** [abiosoft/colima#236]
I use command below:
`docker run -d -p 3306:3306 --privileged=true --name localMysql -v /localPath:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=123456 mysql:latest`

error message: chown: changing ownership of '/var/lib/mysql/': Permission denied

**Comment by abiosoft** [comment]
I would not recommend binding a host volume for database, rather use a docker volume. And if I may ask, is there any reason to run the mysql container as privileged?

You can use a docker volume by specifying a name instead of a host path.
```
docker run -d -p 3306:3306 --name localMysql -v mysqlcache:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=123456 mysql:latest
```
And you can always check docker volumes with `docker volume ls`.

As for the error, this is a known issue. It is a limitation of sshfs that is used by Lima for volume mounts. Work is in progress to to offer 9p mounts as an alternative to sshfs.
