### ISSUE TITLE
Easy way to add docker.sock to container

### ISSUE THREAD

**Issue by anuragagarwal561994** [abiosoft/colima#382]
### Description

At present the docker.sock is available inside the colima vm.

Although it is exposed to the home folder under `~/.colima/docker.sock`, if I want to create a container which has to use this docker.sock it is very difficult.

If I do `docker run -v <absolute path>/.colima/docker.sock:/var/run/docker.sock <image>:<tag>` It is not accessible because of permission issues inside the container.

One workaround for this I have come across is to go in the colima vm and spawn the container from there using `/var/run/docker.sock` command.

I guess it would be great if there is an easy way. Even if docker.sock API is available to connect using the vm IP address that should be fine as well like it happens in case of docker machine.

**Comment by abiosoft** [comment]
It is easier than you think.

```
docker run -v /var/run/docker.sock:/var/run/docker.sock <image>
```

### Explanation

The docker volume mounts files in the VM, not on your host. You are able to access your host files in the containers because they are mounted into the VM as well.

The docker socket location you need to reference is the one in the VM, which is in the default location in the VM.

**Comment by anuragagarwal561994** [comment]
Oh that makes sense, I didn't even try this my bad thanks for helping.
