### ISSUE TITLE
Can't start colima with --network-address on macOS 13 Ventura

### ISSUE THREAD

**Issue by egze** [abiosoft/colima#457]
### Description

Used the command:

```terminal
colima start --cpu 4 --memory 8 --kubernetes --kubernetes-ingress --dns 1.1.1.1 --dns 8.8.8.8 --network-address
```

And got an error:

```
colima start --cpu 4 --memory 8 --kubernetes --kubernetes-ingress --dns 1.1.1.1 --dns 8.8.8.8 --network-address
INFO[0000] starting colima
INFO[0000] runtime: docker+k3s
INFO[0000] preparing network ...                         context=vm
WARN[0015] error starting network: error at 'preparing network': error running [/opt/homebrew/bin/colima daemon status default], output: "time=\"2022-10-27T13:20:08+02:00\" level=fatal msg=\"pid file not found: stat /Users/username/.colima/default/daemon/daemon.pid: no such file or directory\"", err: "exit status 1"  context=vm
WARN[0015] error setting up routable IP address: vmnet ptp socket file not found: stat /Users/username/.colima/default/daemon/vmnet.ptp: no such file or directory
INFO[0015] starting ...                                  context=vm
> Using the existing instance "colima"
> [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/username/.lima/colima/serial.log")
> SSH Local Port: 49899
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] QEMU has exited
> exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see "/Users/username/.lima/colima/ha.stderr.log")
FATA[0015] error starting vm: error at 'starting': exit status 1
make: *** [colima_start] Error 1
```

### Version

Colima Version: 0.4.6
Lima Version: 0.12.0
Qemu Version: 7.1.0

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

1. Install macOS 13 Ventura
2. Run `colima start --cpu 4 --memory 8 --kubernetes --kubernetes-ingress --dns 1.1.1.1 --dns 8.8.8.8 --network-address`

### Expected behaviour

Colima starts and the cluster can be accessed by IP address

**Comment by abiosoft** [comment]
I have been able to reproduce this and currently investigating.

**Comment by jandubois** [comment]
I don't know if this is the same issue, but I've been looking into a problem running k3s 1.24.x+ on macOS Ventura (using Lima).

There is something being done by kubelet that seems to break all the ssh connections with the VM. Happens on both Intel and ARM. Doesn't happen with 1.23.13 or earlier (but I only tried a few versions).

This issue is not related to vde_vmnet; it also happens with just plain libslirp, and it happens with both dockerd and containerd and seems to be triggered by kubelet.

I can run the server portion of k3s fine, but as soon as I also enable the agent, it causes the problem (even after disabling flannel and network policies). We looked at iptables rules, and they all seemed fine. And wouldn't really explain why it happens on Ventura, but not on Monterey.

I'm not sure how to narrow it down further; I don't even really understand how the host OS can effect kubelet in this way. I think it must be some issue in qemu that is just being triggered by kubelet.

So not sure what else to look at; ideas welcome! And I don't even know if you are experiencing the same issue, but you could try using k3s 1.23.13 and see if that one still works for you on Ventura.

**Comment by abiosoft** [comment]
This issue is precisely with vde_vmnet.

```console
dyld[20453]: Library not loaded: /opt/colima/lib/libvdeplug.3.dylib
  Referenced from: <E0AE3F70-E540-36C8-9DA8-6846A194A2E7> /opt/colima/bin/vde_vmnet
  Reason: tried: '/opt/colima/lib/libvdeplug.3.dylib' (mach-o file, but is an incompatible architecture (have 'arm64e', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/colima/lib/libvdeplug.3.dylib' (no such file), '/opt/colima/lib/libvdeplug.3.dylib' (mach-o file, but is an incompatible architecture (have 'arm64e', need 'arm64')), '/usr/local/lib/libvdeplug.3.dylib' (no such file), '/usr/lib/libvdeplug.3.dylib' (no such file, not in dyld cache)
```

Rebuilding the libraries on macOS Ventura should work. I am also planning to migrate to [vmnet_socket](https://github.com/lima-vm/socket_vmnet), this might be the necessary push to get that over the line.

@jandubois yeah, the first thing I did was to check RD's github to see if there are similar issues. I will run general network related tests on my end to see if anything else pops up on Ventura.

**Comment by jandubois** [comment]
> This issue is precisely with vde_vmnet.

Interesting, so this is a different issue for me then. 1.24+ fails for me on Ventura even when running without vde_vmnet. At least sometimes.

Rebuilding things for Ventura also looks messy, e.g. XCode 14.0.1 doesn't seem to include the macOS 13 SDK, and XCode 14.1.0 is still in RC mode. You would think that Apple would release a non-beta SDK by the time they release the OS.

**Comment by abiosoft** [comment]
@jandubois  I am able to start with k3s successfully (without vmnet). I've tried 1.24.x and 1.25.x versions

Though Colima is slightly behind on the Alpine image https://github.com/lima-vm/alpine-lima/commit/010335ee0ab13f54e2e8eb2a30abe3d1b3c6a676. I am not sure if anything has changed to warrant the change in behaviour on RD.

**Comment by abiosoft** [comment]
Can you kindly try with the current development version?

```
brew install --HEAD colima
```

**Comment by egze** [comment]
> Can you kindly try with the current development version?
> 
> ```
> brew install --HEAD colima
> ```

Colima boots now, but now traefik is not started. `--kubernetes-ingress` argument does not exist anymore, but without it, I have no traefik. Is there a new way how to start it?

**Comment by egze** [comment]
I think this is now the correct argument to have traefik `--kubernetes-disable=""`. Can you please confirm that it is the blessed way?

**Comment by abiosoft** [comment]
> I think this is now the correct argument to have traefik `--kubernetes-disable=""`. Can you please confirm that it is the blessed way?

Yeah, that works.

**Comment by egze** [comment]
Thanks ❤️

**Comment by kazajhodo** [comment]
> Can you kindly try with the current development version?
> 
> ```
> brew install --HEAD colima
> ```

Worked for me.
