### ISSUE TITLE
Fresh Colima install uses vmType vz on Mac

### ISSUE THREAD

**Issue by mlhartme** [abiosoft/colima#526]
### Description

A fresh install on my Ventura Mac via Homebrew create a Lima VM with vmType "vz". 

vz is flagged as experimental and causes problems for me. 

Can you adjust Colima to use qemu until vz is more stable?

### Version

Colima Version: 0.5.0
Lima Version: 0.14.1 
Qemu Version: 7.2.0

### Operating System

- [X] macOS Intel
- [ ] macOS M1
- [ ] Linux

### Reproduction Steps

1. brew uninstall colima lima
2. rm -rf ~/.colima ~/.lima
3. brew install colima
4. colima start
5. limectl list

### Expected behaviour

"colima" vm should have type "qemu".

**Comment by SuperFola** [comment]
You should use `colima start --vm-type qemu` to start a colima instance using on qemu, IMHO relying on default values is not a good thing to do, always provide explicitly what you need.

**Comment by mlhartme** [comment]
I didn't know about Lima details like vm types before I hit this problem because Colima did a great job to hide this from me. Am I wrong to expect Colima to pick robust Lima configuration for me?

**Comment by SuperFola** [comment]
> Am I wrong to expect Colima to pick robust Lima configuration for me?

Maybe, but that's because I see colima like a wrapper around lima, easing docker related stuff, while lima is at an even lower level.

**Comment by rfay** [comment]
@mlhartme the option of having vz as an vm type as opposed to qemu just arrived in 0.5.0 of colima, so thats why you hadn't fiddled with vm types before.

**Comment by mlhartme** [comment]
Ok, so why is vz the default for this value?

**Comment by sdemura** [comment]
> You should use `colima start --vm-type qemu` to start a colima instance using on qemu, IMHO relying on default values is not a good thing to do, always provide explicitly what you need.

Disagree. It's bad UX to expect an end user to automatically know to pass `--vm-type qemu` when the README clearly states to just use `colima start` to get up and running.

IMO, colima dev's should not have defaulted to `vz` as the default for Macs for 0.5.0 and left qemu as the default.

**Comment by balajiv113** [comment]
> causes problems for me.

@mlhartme could you specify the problems/issues your are facing ??

**Comment by abiosoft** [comment]
> Ok, so why is vz the default for this value?

@mlhartme it was due to assumptions on our end that native macOS virtualization will provide a better performance all round than qemu. And it is only enabled on supported systems i.e. macOS 13.

One of the things Colima has tried to do is to have _sensible_ defaults i.e. what provides the best experience for the average user. Like you said `colima start` has been all you had to worry about.

Among the most reported issues is related to filesystem access, which virtiofs provides a boost in performance. In fact, it is the main reason for considering other than qemu initially.

Now considering the amount of issues opened in the past few days, I agree and you do have a valid point. Reverting to Qemu as the default is being considered.

Also bear in mind that we would not always get this right, and we rely on feedbacks (like yours) to guide the development.

**Comment by abiosoft** [comment]
https://github.com/abiosoft/colima/releases/tag/v0.5.1
May take a while to appear on brew https://github.com/Homebrew/homebrew-core/pull/118671

**Comment by mlhartme** [comment]
Thank you all for the vivid discussion and the quick solution :)

ps: @[balajiv113](https://github.com/balajiv113) I had problems mounting my home folder into the vz vm
